<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class BaseBlog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('blog');
        $this->hasColumn('url', 'string', 1000, array('type' => 'string', 'notnull' => true, 'length' => '1000'));
        $this->hasColumn('email', 'string', 1000, array('type' => 'string', 'notnull' => true, 'length' => '1000'));
        $this->hasColumn('is_thumbnail', 'boolean', null, array('type' => 'boolean', 'notnull' => true, 'default' => 0));
        $this->hasColumn('thumbnail_url', 'string', 1000, array('type' => 'string', 'length' => '1000'));
        $this->hasColumn('admin_hash', 'string', 1000, array('type' => 'string', 'length' => '1000'));
        $this->hasColumn('public_hash', 'string', 1000, array('type' => 'string', 'length' => '1000'));
        $this->hasColumn('vote_sum', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
        $this->hasColumn('vote_count', 'integer', null, array('type' => 'integer', 'notnull' => true, 'default' => 0));
    }

    public function setUp()
    {
        $this->hasOne('Vote', array('local' => 'id',
                                    'foreign' => 'blog_id',
                                    'onDelete' => 'CASCADE'));

        $this->hasOne('Blog', array('local' => 'id',
                                    'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}